name: bash

on:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        id: version
        run: |
          output=$(echo "hi")
          version=${output/hi/bye}
          echo "PYPI_RELEASE_URL=https://pypi.org/project/calitp-littlepay/$version" >> "$GITHUB_OUTPUT"

      - name: Get color
        env:
          PYPI_RELEASE_URL: ${{ steps.version.outputs.PYPI_RELEASE_URL }}
        run: echo "$PYPI_RELEASE_URL"
