name: Reusable Workflow caller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [published]

env:
  DEPLOYMENT_ENVIRONMENT: ${{ github.event_name != 'release' && github.ref_name || github.event.release.prerelease && 'test' || 'prod' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo $DEPLOYMENT_ENVIRONMENT
        
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    if: github.event_name == 'workflow_dispatch'

  build:
    needs: [call-reusable-workflow]
    if: |
      always() && !cancelled() && needs.call-reusable-workflow.result == 'success'
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!     
