name: Check API

on:
  workflow_dispatch:

jobs:
  check-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        participant: [mst, sacrt, sbmtd]
        env: [qa, prod]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'cal-itp/littlepay'

      - name: Install the littlepay library
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .

      - name: Create config file and set config
        run: |
          cat > config.yaml <<- EOM
          ${{ secrets.config }}
          EOM
          littlepay config config.yaml         

      - name: Run littlepay
        run: | 
          littlepay switch env ${{ matrix.env }}
          littlepay switch participant ${{ matrix.participant }}
